# syntax=docker/dockerfile:1

FROM selenium/standalone-chrome:4.31.0-20250414

ARG DEBIAN_FRONTEND=noninteractive

# Install python3 and pip
RUN _BUILD_TARGET_ARCH=$(uname -m) && \
	echo "BUILDING TARGET ARCHITECTURE: ${_BUILD_TARGET_ARCH}" && \
	sudo rm -rfv /var/lib/apt/lists/* /var/cache/apt/archives/* /tmp/* && \
	sudo apt-get clean -y && \
	sudo apt-get update --fix-missing -o Acquire::CompressionTypes::Order::=gz && \
	sudo apt-get install -y --no-install-recommends \
		python3 \
		python3-pip \
		python3-venv \
		iproute2 && \
	sudo rm -rfv /var/lib/apt/lists/* /var/cache/apt/archives/* /tmp/*

WORKDIR /app
