services:
  subtensor:
    volumes:
      - "./volumes/storage/server.subtensor/data:/tmp"
    # deploy:
    #   replicas: 0
    #   resources:
    #     limits:
    #       cpus: "1.0"
    #       memory: 1G
    ports:
      - "${RT_BT_SUBTENSOR_WS_PORT:-9944}:9944"
    #   - "9945:9945"
    #   - "30334:30334"
    #   - "30335:30335"

  sidecar-btcli:
    environment:
      RT_BT_SUBTENSOR_HOST: subtensor
    volumes:
      - "./volumes/storage/sidecar.btcli/data:${RT_BTCLI_DATA_DIR:-/var/lib/sidecar.btcli}"
      - "./volumes/.vscode-server:/home/rt-user/.vscode-server"
    # deploy:
    #   replicas: 0
    #   resources:
    #     limits:
    #       cpus: "0.25"
    #       memory: 256M
    # command: ["/bin/bash"]

  validator:
    environment:
      RT_BT_SUBTENSOR_HOST: subtensor
    volumes:
      - "./volumes/storage/sidecar.btcli/data:${RT_BTCLI_DATA_DIR:-/var/lib/sidecar.btcli}"
      - "./volumes/storage/agent.validator/data:${RT_VALIDATOR_DATA_DIR:-/var/lib/agent.validator}"
      - "./redteam_core:/app/agent.validator/redteam_core"
      - "./neurons/validator:/app/agent.validator/neurons/validator"
      - "./neurons/validator/scripts/docker/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh"
      - "./volumes/.vscode-server:/home/rt-user/.vscode-server"
    # deploy:
    #   replicas: 0
    #   resources:
    #     limits:
    #       cpus: "8"
    #       memory: 16G
    # command: ["/bin/bash"]

  miner:
    environment:
      RT_BT_SUBTENSOR_HOST: subtensor
    volumes:
      - "./volumes/storage/sidecar.btcli/data:${RT_BTCLI_DATA_DIR:-/var/lib/sidecar.btcli}"
      - "./volumes/storage/agent.miner/data:${RT_MINER_DATA_DIR:-/var/lib/agent.miner}"
      - "./redteam_core:/app/agent.miner/redteam_core"
      - "./neurons/miner:/app/agent.miner/neurons/miner"
      - "./neurons/miner/scripts/docker/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh"
      - "./volumes/.vscode-server:/home/rt-user/.vscode-server"
    # deploy:
    #   replicas: 0
    #   resources:
    #     limits:
    #       cpus: "4"
    #       memory: 8G
    ports:
      - "${RT_MINER_PORT:-8088}:${RT_MINER_PORT:-8088}"
    # command: ["/bin/bash"]

  reward-app:
    environment:
      RT_BT_SUBTENSOR_HOST: subtensor
    volumes:
      - "./volumes/storage/sidecar.btcli/data:${RT_BTCLI_DATA_DIR:-/var/lib/sidecar.btcli}"
      - "./volumes/storage/server.reward-app/data:${RT_REWARD_APP_DATA_DIR:-/var/lib/server.reward-app}"
      - "./redteam_core:/app/server.reward-app/redteam_core"
      - "./neurons/validator:/app/server.reward-app/neurons/validator"
      - "./services/rewarding:/app/server.reward-app/services/rewarding"
      - "./services/rewarding/scripts/docker/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh"
      - "./volumes/.vscode-server:/home/rt-user/.vscode-server"
    # deploy:
    #   replicas: 0
    #   resources:
    #     limits:
    #       cpus: "8"
    #       memory: 16G
    ports:
      - "${RT_REWARD_APP_PORT:-47920}:${RT_REWARD_APP_PORT:-47920}"
    # command: ["/bin/bash"]
